---
- name: Generate an SSH key-pair
  command: "ssh-keygen -q -t rsa -N '' -C 'Aegir SSH keypair' -f {{ aegir_root }}/.ssh/id_rsa"
  args:
    creates: "{{ aegir_root }}/.ssh/id_rsa"
  become: yes
  become_user: "{{ aegir_user }}"
